import turtle
turtle.setup(650,350,200,200)
turtle.penup()
turtle.fd(-60)
turtle.pendown()
turtle.pensize(5)
turtle.pencolor("red")
turtle.penup()
turtle.fd(30)
turtle.seth(0)
for i in (0,90,180):
    turtle.seth(i)
    turtle.fd(30)
    turtle.pendown()
    turtle.fd(60)
    turtle.penup()
    turtle.fd(30)
turtle.seth(-90)
turtle.fd(30)
turtle.pendown()
turtle.fd(60)
turtle.done()
